version: '3.8'

services:
  app:
    working_dir: /code
    build:
      context: .
      dockerfile: buildfiles/app.Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./artifacts
        target: /code/artifacts
      - type: bind
        source: ./src
        target: /code/src
    user: root

    entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8080