version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: buildfiles/app.Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/code/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080
    restart: always
